# Generated by Django 4.0.6 on 2022-08-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_post_excerpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCounter',
            fields=[
                ('count', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
