# Generated by Django 4.0.6 on 2022-08-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_postcounter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcounter',
            options={'verbose_name': 'Post Counter'},
        ),
    ]
